### ISSUE TITLE
UUID-Feld für Lernelemente

### ISSUE THREAD

**Issue by Glutamat42** [ProjektAdLer/MoodlePluginLocal#14]
**User Story**

Das Authorentool soll allen Lernelementen eine UUID vergeben, die vom Moodle-Plugin ausgelesen wird und zum Mapping referenzieren der Lernelemente durch das Backend genutzt werden können. So wird die Notwendigkeit von aktuell genutzen fehleranfälligen Workarounds entfallen. 
Das Backend kann dann entweder ein Mapping zwischen allen UUIDs und Moodle-IDs abfragen oder die UUIDs statt moodle IDs in bei der Kommunikation mit dem Plugin nutzen.

**Akzeptanzkriterien**

- [ ] Akzeptanzkriterium 1
- [ ] Akzeptanzkriterium 2

**Definition of Ready**

- [ ] User Story ist klein genug für Sprint
- [ ] User Story ist für jeden Beteiligten klar verständlich
- [ ] User Story Aufwand ist geschätzt
- [ ] User Story hat Akzeptanzkriterien
- [ ] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [ ] User Story Ursprung ist bekannt (Stakeholder)
- [ ] User Story ist Release zugewiesen

**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [ ] Die Implementierung ist in GitHub
- [ ] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [ ] Die Codekonventionen sind eingehalten
- [ ] Unittestabdeckung muss größer 90% sein
- [ ] Alle Tests müssen bestanden sein
- [ ] Technische Dokumentation angelegt (Aktivitätsdiagramm in Issue)
- [ ] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [ ] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [ ] Changelog angelegt
- [ ] Es gibt keine bekannten Bugs

**Comment by philgei** [comment]
Eventuell bietet Moodle dieses Feature. In der Neuen API gibt es ein leeres feld in der Lernwelt, welches sich genau danach anhört

**Comment by Glutamat42** [comment]
konvertierung zu / zwischen cmid (und für kurse) und contextid

**Comment by Glutamat42** [comment]
implemented
